{% set name = "ubergauss" %}
{% set version = "0.0.80" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ubergauss-{{ version }}.tar.gz
  sha256: 60985bab410ae729b4f78d9f0916d36e1d00597a75e58da629533848eba990de

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - dill
    - lmz
    - numpy
    - python >=3.8
    - scikit-learn
    - scipy

test:
  imports:
    - ubergauss
    - ubergauss.optimization
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/smautner/ubergauss
  summary: sklearn clustering, betweenGaussian and diagonal-max-dist kneepoint detection
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - smautner
